### ISSUE TITLE
Crash on scanner.provider.traversal

### ISSUE THREAD

**Issue by HenryHoggard** [ReversecLabs/drozer#86]
##### EDIT

Fixed path errors, still crashes.
Running Android 4.0.0 emulator

Every time I run scanner.provider.traversal it crashes on the very last app to scan. I have tried other modules which work fine however this crashes without fail.

I then cannot connect to the agent so I have to restart drozer server.
I have added dx to the path and it still seems to error.
##### Drozer Log

```
Scanning org.awallet.free...
Scanning org.r3pek.wirelesspasswords...
Scanning si.url.rpr...
Scanning spc.PassDefPack...
Scanning uk.co.kuffs.free.passwordsafe...
Could not find dx.
Ensure that dx is installed and on your PATH. If this error persists please add the path to your .drozer_config.
Could not find javac.
Ensure that javac is installed and on your PATH. If this error persists please add the path to your .drozer_config.
We lost your drozer session.

For some reason the mobile Agent has stopped responding. You will need to restart it, and try again.

```
##### ADB Logcat

```
 783): GC_CONCURRENT freed 885K, 53% free 6218K/12999K, paused 7ms+7ms
D/dalvikvm(  783): GC_CONCURRENT freed 404K, 53% free 6215K/12999K, paused 5ms+3ms
E/mercury-native(  783): Error opening file : /data/app/org.r3pek.wirelesspasswords-1.odex
D/dalvikvm(  783): GC_CONCURRENT freed 414K, 53% free 6238K/12999K, paused 4ms+2ms
E/mercury-native(  783): Error opening file : /data/app/si.url.rpr-1.odex
D/dalvikvm(  783): GC_CONCURRENT freed 427K, 53% free 6213K/12999K, paused 8ms+2ms
D/dalvikvm(  783): GC_CONCURRENT freed 393K, 52% free 6242K/12999K, paused 2ms+7ms
E/mercury-native(  783): Error opening file : /data/app/spc.PassDefPack-1.odex
D/dalvikvm(  783): GC_CONCURRENT freed 433K, 52% free 6267K/12999K, paused 7ms+5ms
D/dalvikvm(  783): GC_CONCURRENT freed 444K, 53% free 6220K/12999K, paused 2ms+6ms
D/dalvikvm(  783): GC_FOR_ALLOC freed 277K, 53% free 6200K/12999K, paused 24ms
I/dalvikvm-heap(  783): Grow heap (frag case) to 7.765MB for 1368884-byte allocation
D/dalvikvm(  783): GC_CONCURRENT freed <1K, 43% free 7537K/12999K, paused 7ms+3ms
D/dalvikvm(  783): GC_FOR_ALLOC freed <1K, 43% free 7536K/12999K, paused 26ms
I/dalvikvm-heap(  783): Grow heap (frag case) to 8.417MB for 684450-byte allocation
D/dalvikvm(  783): GC_FOR_ALLOC freed 1336K, 48% free 6868K/12999K, paused 22ms
I/dalvikvm-heap(  783): Grow heap (frag case) to 7.765MB for 684499-byte allocation
D/dalvikvm(  783): GC_CONCURRENT freed 0K, 43% free 7537K/12999K, paused 5ms+2ms
D/dalvikvm(  783): GC_FOR_ALLOC freed 668K, 48% free 6868K/12999K, paused 28ms
I/dalvikvm-heap(  783): Grow heap (frag case) to 7.765MB for 684507-byte allocation
D/dalvikvm(  783): GC_FOR_ALLOC freed 0K, 43% free 7537K/12999K, paused 25ms
D/dalvikvm(  783): GC_FOR_ALLOC freed 0K, 43% free 7537K/12999K, paused 25ms
I/dalvikvm-heap(  783): Grow heap (frag case) to 8.417MB for 684499-byte allocation
D/dalvikvm(  783): GC_CONCURRENT freed 0K, 37% free 8205K/12999K, paused 6ms+3ms
E/mercury-native(  783): Error opening file : /data/app/uk.co.kuffs.free.passwordsafe-1.odex
E/DatabaseUtils(  341): Writing exception to parcel
E/DatabaseUtils(  341): java.lang.IllegalStateException: Unknown URL: content://media/external/audio/search/fancy//../../../../../../../../../../../../../../../../etc/hosts
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.query(MediaProvider.java:2235)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openFileHelper(ContentProvider.java:735)
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.openFile(MediaProvider.java:3761)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openAssetFile(ContentProvider.java:715)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:823)
E/DatabaseUtils(  341):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:249)
E/DatabaseUtils(  341):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  341):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  341):     at dalvik.system.NativeStart.run(Native Method)
E/ActivityThread(  783): Failed to find provider info for com.dashlane.android.browser
E/DatabaseUtils(  223): Writing exception to parcel
E/DatabaseUtils(  223): java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts/.*/photo//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_CONTACTS
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  223):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  223):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  223):     at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(  783): GC_CONCURRENT freed 2719K, 52% free 6248K/12999K, paused 3ms+7ms
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.telephony.SmsProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_SMS or android.permission.WRITE_SMS
E/DatabaseUtils(  358): Writing exception to parcel
E/DatabaseUtils(  358): java.lang.SecurityException: Permission Denial: reading com.android.mms.SuggestionsProvider uri content://com.android.mms.SuggestionsProvider/search_suggest_shortcut/../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_SMS
E/DatabaseUtils(  358):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  358):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  358):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  358):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  358):     at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager(   77): Permission Denial: opening provider com.android.phone.IccProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
E/DatabaseUtils(  223): Writing exception to parcel
E/DatabaseUtils(  223): java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://contacts/live_folders/people_with_phones//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_CONTACTS
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  223):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  223):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  223):     at dalvik.system.NativeStart.run(Native Method)
E/DatabaseUtils(  545): Writing exception to parcel
E/DatabaseUtils(  545): java.lang.SecurityException: Permission Denial: reading com.android.browser.provider.BrowserProvider2 uri content://browser/bookmarks//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires com.android.browser.permission.READ_HISTORY_BOOKMARKS
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  545):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  545):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  545):     at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(  783): GC_CONCURRENT freed 470K, 53% free 6235K/12999K, paused 7ms+6ms
E/ActivityThread(  783): Failed to find provider info for com.dashlane.android.browser.home
E/DatabaseUtils(  358): Writing exception to parcel
E/DatabaseUtils(  358): java.lang.SecurityException: Permission Denial: reading com.android.mms.SuggestionsProvider uri content://com.android.mms.SuggestionsProvider/search_suggest_query//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_SMS
E/DatabaseUtils(  358):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  358):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  358):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  358):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  358):     at dalvik.system.NativeStart.run(Native Method)
E/ActivityThread(  783): Failed to find provider info for contacts.*
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
D/dalvikvm(  783): GC_CONCURRENT freed 440K, 52% free 6246K/12999K, paused 2ms+6ms
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.telephony.MmsSmsProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_SMS or android.permission.WRITE_SMS
E/ActivityThread(  783): Failed to find provider info for com.google.android.partnersetup.rlzappprovider
E/DatabaseUtils(  223): Writing exception to parcel
E/DatabaseUtils(  223): java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://contacts/live_folders/people//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_CONTACTS
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  223):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  223):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  223):     at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(  783): GC_CONCURRENT freed 439K, 52% free 6250K/12999K, paused 6ms+6ms
W/ActivityManager(   77): Permission Denial: opening provider com.android.launcher2.LauncherProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires com.android.launcher.permission.READ_SETTINGS or com.android.launcher.permission.WRITE_SETTINGS
W/ActivityManager(   77): Permission Denial: opening provider com.android.phone.IccProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
W/ActivityManager(   77): Permission Denial: opening provider com.android.email.provider.EmailProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires com.android.email.permission.ACCESS_PROVIDER or com.android.email.permission.ACCESS_PROVIDER
D/dalvikvm(  783): GC_CONCURRENT freed 459K, 52% free 6243K/12999K, paused 6ms+8ms
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.telephony.MmsSmsProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_SMS or android.permission.WRITE_SMS
E/DatabaseUtils(  545): Writing exception to parcel
E/DatabaseUtils(  545): java.lang.SecurityException: Permission Denial: reading com.android.browser.provider.BrowserProvider2 uri content://com.android.browser//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires com.android.browser.permission.READ_HISTORY_BOOKMARKS
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  545):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  545):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  545):     at dalvik.system.NativeStart.run(Native Method)
E/ActivityThread(  783): Failed to find provider info for com.dashlane.android.browser
W/ActivityManager(   77): Permission denied: checkComponentPermission() owningUid=10042
W/ActivityManager(   77): Permission denied: checkComponentPermission() owningUid=10042
W/ActivityManager(   77): Permission Denial: opening provider mono.MonoRuntimeProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) that is not exported from uid 10042
D/dalvikvm(  783): GC_CONCURRENT freed 434K, 53% free 6236K/12999K, paused 4ms+5ms
W/ActivityManager(   77): Permission Denial: opening provider com.android.launcher2.LauncherProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires com.android.launcher.permission.READ_SETTINGS or com.android.launcher.permission.WRITE_SETTINGS
E/DatabaseUtils(  545): Writing exception to parcel
E/DatabaseUtils(  545): java.lang.SecurityException: Permission Denial: reading com.android.browser.provider.BrowserProvider2 uri content://com.android.browser/bookmarks/search_suggest_query//../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires com.android.browser.permission.READ_HISTORY_BOOKMARKS
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  545):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  545):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  545):     at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(  783): GC_CONCURRENT freed 425K, 52% free 6248K/12999K, paused 5ms+4ms
E/DatabaseUtils(  341): Writing exception to parcel
E/DatabaseUtils(  341): java.lang.IllegalStateException: Unknown URL: content://media/external/video/../../../../../../../../../../../../../../../../etc/hosts
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.query(MediaProvider.java:2235)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openFileHelper(ContentProvider.java:735)
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.openFile(MediaProvider.java:3761)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openAssetFile(ContentProvider.java:715)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:823)
E/DatabaseUtils(  341):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:249)
E/DatabaseUtils(  341):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  341):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  341):     at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.contacts.CallLogProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
D/dalvikvm(  341): GC_CONCURRENT freed 402K, 14% free 5915K/6855K, paused 4ms+3ms
E/DatabaseUtils(  341): Writing exception to parcel
E/DatabaseUtils(  341): java.lang.IllegalArgumentException: Unknown URI: content://downloads/download/../../../../../../../../../../../../../../../../etc/hosts
E/DatabaseUtils(  341):     at com.android.providers.downloads.DownloadProvider.query(DownloadProvider.java:809)
E/DatabaseUtils(  341):     at com.android.providers.downloads.DownloadProvider.openFile(DownloadProvider.java:1127)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openAssetFile(ContentProvider.java:715)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:823)
E/DatabaseUtils(  341):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:249)
E/DatabaseUtils(  341):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  341):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  341):     at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager(   77): Permission Denial: opening provider com.android.email.provider.EmailProvider from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires com.android.email.permission.ACCESS_PROVIDER or com.android.email.permission.ACCESS_PROVIDER
E/DatabaseUtils(  545): Writing exception to parcel
E/DatabaseUtils(  545): java.lang.SecurityException: Permission Denial: reading com.android.browser.provider.BrowserProvider2 uri content://com.android.browser/../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires com.android.browser.permission.READ_HISTORY_BOOKMARKS
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  545):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  545):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  545):     at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(  783): GC_CONCURRENT freed 444K, 52% free 6261K/12999K, paused 7ms+6ms
E/DatabaseUtils(  545): Writing exception to parcel
E/DatabaseUtils(  545): java.lang.SecurityException: Permission Denial: reading com.android.browser.provider.BrowserProvider2 uri content://com.android.browser/bookmarks/search_suggest_query/../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires com.android.browser.permission.READ_HISTORY_BOOKMARKS
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  545):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  545):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  545):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  545):     at dalvik.system.NativeStart.run(Native Method)
E/DatabaseUtils(  223): Writing exception to parcel
E/DatabaseUtils(  223): java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://contacts/../../../../../../../../../../../../../../../../etc/hosts from pid=783, uid=10086 requires android.permission.READ_CONTACTS
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:295)
E/DatabaseUtils(  223):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:248)
E/DatabaseUtils(  223):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  223):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  223):     at dalvik.system.NativeStart.run(Native Method)
E/DatabaseUtils(  341): Writing exception to parcel
E/DatabaseUtils(  341): java.lang.IllegalStateException: Unknown URL: content://media/external/audio/search/fancy/../../../../../../../../../../../../../../../../etc/hosts
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.query(MediaProvider.java:2235)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openFileHelper(ContentProvider.java:735)
E/DatabaseUtils(  341):     at com.android.providers.media.MediaProvider.openFile(MediaProvider.java:3761)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openAssetFile(ContentProvider.java:715)
E/DatabaseUtils(  341):     at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:823)
E/DatabaseUtils(  341):     at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:249)
E/DatabaseUtils(  341):     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:287)
E/DatabaseUtils(  341):     at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils(  341):     at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager(   77): Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{412f3e48 783:com.mwr.dz:remote/10086} (pid=783, uid=10086) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
^C
```

**Comment by anjingweixiao** [comment]
楼主有没有解决问题的方法啊

**Comment by HenryHoggard** [comment]
@anjingweixiao 我已經更新了最新的版本，新版本運作正常

**Comment by Tangyiming** [comment]
@HenryHoggard 你好，我用的2.3.4 运行所有scanner方法都会crash 失去连接。请问你用的是哪个版本呢，有什么相关解决办法吗

**Comment by JohnCUMT** [comment]
you can use adb kill-server,then using adb start-server, adb forward tcp:31415 tcp:31415 and drozer console connect
